# Generated by Django 2.2.5 on 2019-09-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
        ('sala', '0002_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.AddField(
            model_name='aluno',
            name='prof_favorito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='professor.Professor'),
            preserve_default=False,
        ),
    ]
