# Generated by Django 2.2.5 on 2019-09-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default=1, max_length=50, verbose_name='email'),
            preserve_default=False,
        ),
    ]
